export enum DeliveryNoteSourceType {
    ORDER = 'ORDER',
    DIRECT = 'DIRECT',
    INVOICE_AUTOMATIC = 'INVOICE_AUTOMATIC'
}

export enum DeliveryNoteStatus {
    NOT_INVOICED = 'NOT_INVOICED',
    PARTIALLY_INVOICED = 'PARTIALLY_INVOICED',
    INVOICED = 'INVOICED',
    CANCELLED = 'CANCELLED',
    TESLIM_EDILDI = 'TESLIM_EDILDI',
    BEKLEMEDE = 'BEKLEMEDE',
    FATURAYA_BAGLANDI = 'FATURAYA_BAGLANDI',
    IPTAL = 'IPTAL',
}
