services:
  backend-staging:
    container_name: azemshopping_backend
    build:
      context: ../../api-stage/server
      dockerfile: Dockerfile.dev
    env_file:
      - .env.azemshopping
    environment:
      - NODE_ENV=development
    volumes:
      - ../../api-stage/server:/app/server
      - /app/server/node_modules
    networks: [ azemshopping_net ]
    ports:
      - "4041:3000"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://0.0.0.0:3000/api/health" ]
      interval: 30s
      timeout: 3s
      retries: 12
      start_period: 30s
    restart: unless-stopped

  user-panel-staging:
    container_name: azemshopping_panel
    build:
      context: ../../panel-stage/client
      dockerfile: Dockerfile.dev
    ports:
      - "4021:3000"
    env_file:
      - .env.azemshopping
    environment:
      NODE_ENV: development
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      API_PROXY_TARGET: "http://azemshopping_backend:3000"
      NEXT_PUBLIC_API_URL: http://localhost:4041
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4041
    volumes:
      - ../../panel-stage/client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - azemshopping_net
    depends_on:
      - backend-staging
    restart: unless-stopped

networks:
  azemshopping_net:
    name: azemshopping_net
    driver: bridge
